# VSCode: Shift + Alt + P
openapi: '3.0.3'
info:
  title: WSLManager API
  version: '1.0'
servers:
  - url: http://localhost:7711/api/v1
paths:
  /distributions:
    get:
      tags:
        - distributions
      summary: ディストリビューションのリストを取得する
      description: ディストリビューション
      responses:
        '200':
          description: ディストリビューションリスト
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  items:
                    $ref: './responses/distribution.yaml#/components/schemas/response_distribution'
                  example:
                    isDefault: true
                    name: 'Ubuntu'
                    state: 'Running'
                    version: '2.0'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: './responses/error.yaml#/components/schemas/response_error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: './responses/error.yaml#/components/schemas/response_error'
    post:
      tags:
        - distributions
      summary: ディストリビューションをインポートして新規作成する
      description: ディストリビューションをインポートして新規作成する
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: './requests/distribution_post.yaml#/components/schemas/request_distribution_post'
      responses:
        '200':
          description: ディストリビューションリスト
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  items:
                    $ref: './responses/distribution.yaml#/components/schemas/response_distribution'
                  example:
                    isDefault: true
                    name: 'Ubuntu'
                    state: 'Running'
                    version: '2.0'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: './responses/error.yaml#/components/schemas/response_error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: './responses/error.yaml#/components/schemas/response_error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: './responses/error.yaml#/components/schemas/response_error'

  /distributions/{distribution}:
    get:
      tags:
        - distributions
      summary: ディストリビューションを取得する
      description: ディストリビューションを取得する
      parameters:
        - name: 'distribution'
          in: path
          required: true
          schema: { type: string }
      responses:
        '200':
          description: ディストリビューション
          content:
            application/json:
              schema:
                $ref: './responses/distribution.yaml#/components/schemas/response_distribution'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: './responses/error.yaml#/components/schemas/response_error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: './responses/error.yaml#/components/schemas/response_error'

    put:
      tags:
        - distributions
      summary: ディストリビューションのコマンド実行
      description: ディストリビューションのコマンド実行
      parameters:
        - name: 'distribution'
          in: path
          required: true
          schema: { type: string }
      requestBody:
        content:
          application/json:
            schema:
              $ref: './requests/distribution_put.yaml#/components/schemas/request_distribution_put'
      responses:
        '200':
          description: ディストリビューションリスト
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  items:
                    $ref: './responses/distribution.yaml#/components/schemas/response_distribution'
                  example:
                    isDefault: true
                    name: 'Ubuntu'
                    state: 'Running'
                    version: '2.0'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: './responses/error.yaml#/components/schemas/response_error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: './responses/error.yaml#/components/schemas/response_error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: './responses/error.yaml#/components/schemas/response_error'
    delete:
      tags:
        - distributions
      summary: ディストリビューションの削除
      description: ディストリビューションの削除
      parameters:
        - name: 'distribution'
          in: path
          required: true
          schema: { type: string }
      requestBody:
        content:
          application/json:
            schema:
              $ref: './requests/distribution_delete.yaml#/components/schemas/request_distribution_delete'
      responses:
        '200':
          description: ディストリビューションリスト
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  items:
                    $ref: './responses/distribution.yaml#/components/schemas/response_distribution'
                  example:
                    isDefault: true
                    name: 'Ubuntu'
                    state: 'Running'
                    version: '2.0'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: './responses/error.yaml#/components/schemas/response_error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: './responses/error.yaml#/components/schemas/response_error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: './responses/error.yaml#/components/schemas/response_error'

  /online-distributions:
    get:
      tags:
        - online-distributions
      summary: オンラインディストリビューションのリスト取得
      description: オンラインディストリビューションのリスト取得
      responses:
        '200':
          description: オンラインディストリビューションリスト
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  items:
                    $ref: './responses/online_distribution.yaml#/components/schemas/response_online_distribution'
                  example:
                    isDefault: true
                    name: 'Ubuntu'
                    state: 'Running'
                    version: '2.0'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: './responses/error.yaml#/components/schemas/response_error'
    post:
      tags:
        - online-distributions
      summary: オンラインディストリビューションをインストール
      description: オンラインディストリビューションをインストール
      requestBody:
        content:
          application/json:
            schema:
              $ref: './requests/online_distribution_post.yaml#/components/schemas/request_online_distribution_post'
      responses:
        '200':
          description: ディストリビューションリスト
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  items:
                    $ref: './responses/distribution.yaml#/components/schemas/response_distribution'
                  example:
                    isDefault: true
                    name: 'Ubuntu'
                    state: 'Running'
                    version: '2.0'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: './responses/error.yaml#/components/schemas/response_error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: './responses/error.yaml#/components/schemas/response_error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: './responses/error.yaml#/components/schemas/response_error'
