/* tslint:disable */
/* eslint-disable */
/**
 * WSLManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseDistribution
 */
export interface ResponseDistribution {
    /**
     * デフォルトの場合true
     * @type {boolean}
     * @memberof ResponseDistribution
     */
    isDefault: boolean;
    /**
     * ディストリビューション名
     * @type {string}
     * @memberof ResponseDistribution
     */
    name: string;
    /**
     * 状態
     * @type {string}
     * @memberof ResponseDistribution
     */
    state: string;
    /**
     * WSLのバージョン
     * @type {string}
     * @memberof ResponseDistribution
     */
    version: string;
}

/**
 * Check if a given object implements the ResponseDistribution interface.
 */
export function instanceOfResponseDistribution(value: object): value is ResponseDistribution {
    if (!('isDefault' in value) || value['isDefault'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function ResponseDistributionFromJSON(json: any): ResponseDistribution {
    return ResponseDistributionFromJSONTyped(json, false);
}

export function ResponseDistributionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseDistribution {
    if (json == null) {
        return json;
    }
    return {
        
        'isDefault': json['isDefault'],
        'name': json['name'],
        'state': json['state'],
        'version': json['version'],
    };
}

export function ResponseDistributionToJSON(value?: ResponseDistribution | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'isDefault': value['isDefault'],
        'name': value['name'],
        'state': value['state'],
        'version': value['version'],
    };
}

