/* tslint:disable */
/* eslint-disable */
/**
 * WSLManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ResponseDistribution,
} from '../models/index';
import {
    ResponseDistributionFromJSON,
    ResponseDistributionToJSON,
} from '../models/index';

export interface ApiV1DistributionsDistributionGetRequest {
    distribution: string;
}

/**
 * 
 */
export class DistributionsApi extends runtime.BaseAPI {

    /**
     * ディストリビューション
     * ディストリビューションを取得する
     */
    async apiV1DistributionsDistributionGetRaw(requestParameters: ApiV1DistributionsDistributionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseDistribution>> {
        if (requestParameters['distribution'] == null) {
            throw new runtime.RequiredError(
                'distribution',
                'Required parameter "distribution" was null or undefined when calling apiV1DistributionsDistributionGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/distributions/{distribution}`.replace(`{${"distribution"}}`, encodeURIComponent(String(requestParameters['distribution']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseDistributionFromJSON(jsonValue));
    }

    /**
     * ディストリビューション
     * ディストリビューションを取得する
     */
    async apiV1DistributionsDistributionGet(requestParameters: ApiV1DistributionsDistributionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseDistribution> {
        const response = await this.apiV1DistributionsDistributionGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ディストリビューション
     * ディストリビューションのリストを取得する
     */
    async apiV1DistributionsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Array<ResponseDistribution>>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/distributions`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * ディストリビューション
     * ディストリビューションのリストを取得する
     */
    async apiV1DistributionsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Array<ResponseDistribution>>> {
        const response = await this.apiV1DistributionsGetRaw(initOverrides);
        return await response.value();
    }

}
