// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * WSLManager API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 */

package http

import (
  "github.com/gin-gonic/gin"
  "wslmanager/http/controllers"
)

type DistributionsAPIController interface { 
  DistributionsDistributionDelete(*gin.Context)
  DistributionsDistributionGet(*gin.Context)
  DistributionsDistributionPost(*gin.Context)
  DistributionsDistributionPut(*gin.Context)
  DistributionsGet(*gin.Context)
}

func registerDistributionsAPIRoutes(e *gin.Engine, r DistributionsAPIController) {
  e.DELETE("/api/v1/distributions/:distribution", r.DistributionsDistributionDelete)
  e.GET("/api/v1/distributions/:distribution", r.DistributionsDistributionGet)
  e.POST("/api/v1/distributions/:distribution", r.DistributionsDistributionPost)
  e.PUT("/api/v1/distributions/:distribution", r.DistributionsDistributionPut)
  e.GET("/api/v1/distributions", r.DistributionsGet)
}

func RegisterRoutes(e *gin.Engine) {
  registerDistributionsAPIRoutes(e, &controllers.DistributionsAPI{})
}
